config/routes.rb
Rails.application.routes.draw do
  resources :reviews, only: [:new, :create]
  patch '/jobs/:id/accept', to: 'jobs#accept', as: 'accept'
  patch '/jobs/:id/complete', to: 'jobs#complete', as: 'complete'
  patch '/jobs/:id/cancel', to: 'jobs#cancel', as: 'cancel'
  patch '/jobs/:id/uncancel', to: 'jobs#uncancel', as: 'uncancel'
  patch '/jobs/:id/archive', to: 'jobs#archived', as: 'archive'
  get '/jobs/my-jobs', to: 'jobs#my_jobs', as: 'my-jobs'
  resources :jobs
  resources :users, except: [:index]
  root :to => "mains#home"
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/self', to: 'users#myself', as: 'self'

  get '/:fail', to: 'mains#not_found'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :poster, class_name: "User"
  belongs_to :mover, class_name: "User", optional: true

  has_many :furniture_jobs
  has_many :furnitures, through: :furniture_jobs
  has_many :reviews
  validates :title, presence: true
  validate :time_validation, :furniture_validation

  accepts_nested_attributes_for :furnitures

  def time_validation
    if date < Time.now
      errors.add(:date, "can't be in the past")
    end
  end

  def furniture_validation
    if self.furnitures.empty?
      errors.add(:furniture, "can't be empty")
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy, :accept, :complete, :cancel, :uncancel, :archived]
  skip_before_action :authorized, only: [:index]

  # GET /jobs
  # GET /jobs.json
  def index
    if params[:filter_status] && params[:filter_status] != "0"
      @jobs = Job.where("status LIKE ?", "#{params[:filter_status]}")
    elsif params[:filter_furniture] && params[:filter_furniture] != "0"
      furniture = Furniture.find_by(category: "#{params[:filter_furniture]}")
      @jobs = Job.all.select do |j|
        j.furnitures.include?(furniture)
      end
    else
      @jobs = Job.all.where.not(status: "Archived")
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def accept
    @job.mover_id = session[:user_id]
    @job.status = "Accepted"
    @job.save
    redirect_to @job
  end

  def complete
    @job.status = "Completed"
    @job.save
    redirect_to @job
  end

  def cancel
    if @job.poster.id == session[:user_id]
      @job.status = "Canceled"
    elsif @job.mover.id == session[:user_id]
      @job.status = "Pending"
      @job.mover = nil
    end
    @job.save
    redirect_to @job
  end

  def uncancel
    if @job.mover
      @job.status = "Accepted"
    else
      @job.status = "Pending"
    end
    @job.save
    redirect_to @job
  end

  def archived
    @job.status = "Archived"
    @job.save
    redirect_to my_jobs_path
  end

  def my_jobs
    @posted_jobs = User.find(session[:user_id]).posted_jobs.where.not(status: "Archived")
    @accepted_jobs = User.find(session[:user_id]).mover_jobs.where.not(status: "Archived")
    @archived_posts = User.find(session[:user_id]).posted_jobs.where(status: "Archived")
    @archived_jobs = User.find(session[:user_id]).mover_jobs.where(status: "Archived")
    render :my_jobs
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :date, :status, :poster_id, :description, furniture_ids: [])
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2>Sorry, we can't post this job.</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.hidden_field :poster_id, :value => session[:user_id] %>
  </div>

  <div class="field">
    <%= form.hidden_field :status, :value => 'Pending' %>
  </div>

  <div class="field">
    <%= form.label "Furniture" %>
    <%= form.collection_check_boxes :furniture_ids, Furniture.all, :id, :category do |f| %>
      <%= f.label { f.check_box + " " + f.text } %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date, start_year: 2019 %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control"%>
  </div>

  <div class="actions">
    <%= form.submit "Create Pickup", class: "btn btn-outline-secondary"  %>
  </div>

<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>


<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Pickups</h1>
<div class="job-card">
  <div class="filter-forms">
    <%= form_tag(jobs_path, method: "get", class: "dropdown") %>
      <label for="filter_status"><strong>Filter by status</strong></label>
      <select name="filter_status">
        <option value="0">All</option>
        <option value="Pending">Pending</option>
        <option value="Accepted">Accepted</option>
        <option value="Completed">Completed</option>
        <option value="Canceled">Canceled</option>
      </select>
    <%= submit_tag "Filter", class: "btn btn-outline-secondary small-btn" %>
  </div>

  <div class="filter-forms">
    <%= form_tag(jobs_path, method: "get") %>
      <label for="filter_furniture"><strong>Filter by furniture</strong></label>
      <select name="filter_furniture">
        <option value="0">All</option>
        <option value="Sofa">Sofa</option>
        <option value="Television">Television</option>
        <option value="Bed">Bed</option>
        <option value="Chair">Chair</option>
        <option value="Shelf">Shelf</option>
        <option value="Lamp">Lamp</option>
        <option value="Table">Table</option>
        <option value="Plant(s)">Plant(s)</option>
        <option value="Curtain(s)">Curtain(s)</option>
        <option value="Storage container">Storage container</option>
      </select>
    <%= submit_tag "Filter", class: "btn btn-outline-secondary small-btn" %>
  </div>

  <table style="width:85%;">
    <thead>
      <tr>
        <th>Title</th>
        <th>Date</th>
        <th>Status</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @jobs.each do |job| %>
        <tr>
          <td><%= link_to job.title, job %></td>
          <td><%= link_to job.date.time.strftime("%b %d, %Y at %I:%M%P"), job %></td>
          <td><%= link_to job.status, job %></td>
      <% end %>
    </tbody>
  </table>
</div>
<br>
<%= button_to 'New Pickup', new_job_path, method: :get, class: "btn btn-outline-secondary" %>

app/views/jobs/my_jobs.html.erb
<p id="notice"><%= notice %></p>

<h1>My Pickups</h1>

<h4>Posted Pickups</h4>

<% @posted_jobs.each_slice(3) do |jobs| %>
  <div class="row">
    <% jobs.each do |job| %>
      <div class="col-sm-3 card ">
        <%= link_to job.title, job %>
        <%= link_to job.date.time.strftime("%b %d, %Y at %I:%M%P"), job %>
        <%= link_to job.status, job %>
      </div>
    <% end %>
  </div>
<% end %>

<br>
<%= button_to 'Post a New Pickup', new_job_path, method: :get, class: "btn btn-outline-secondary" %>
<br>

<h4>Accepted Pickups</h4>
<% @accepted_jobs.each_slice(3) do |jobs| %>
  <div class="row">
    <% jobs.each do |job| %>
      <div class="col-sm-3 card ">
        <%= link_to job.title, job %>
        <%= link_to job.date.time.strftime("%b %d, %Y at %I:%M%P"), job %>
        <%= link_to job.status, job %>
      </div>
    <% end %>
  </div>
<% end %>

<br>
<%= button_to 'Find a New Pickup', jobs_path, method: :get, class: "btn btn-outline-secondary" %>

<br>


<h4>Past Posts</h4>
<% @archived_posts.each_slice(3) do |jobs| %>
  <div class="row">
    <% jobs.each do |job| %>
      <div class="col-sm-3 card">
        <%= link_to job.title, job %>
        <%= link_to job.date.time.strftime("%b %d, %Y"), job %>
      </div>
    <% end %>
  </div>
<% end %>

<br>

<h4>Past Pickups</h4>
<% @archived_jobs.each_slice(3) do |jobs| %>
  <div class="row">
    <% jobs.each do |job| %>
      <div class="col-sm-3 card">
        <%= link_to job.title, job %>
        <%= link_to job.date.time.strftime("%b %d, %Y"), job %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/jobs/new.html.erb
<h1>New Pickup</h1>
<div class="job-card">
<%= render 'form', job: @job %>



<%= link_to 'Back', jobs_path, class: "btn btn-outline-secondary" %>
</div>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>
<div class="job-card">
  <h1>
  <% if @job.poster.id == session[:user_id] || (@job.mover && @job.mover.id == session[:user_id]) %>
    Your
  <% else %>
    <%= @job.poster.name %>'s
  <% end %>
  <%= @job.status %> Pickup
  </h1>
  <div class="row">
      <div class="col-md-8">
        <p>
          <strong>Title:</strong>
          <%= @job.title %>
        </p>

        <p>
          <strong>Description:</strong>
          <%= @job.description %>
        </p>


        <p>
          <strong>Date:</strong>
          <%= @job.date.time.strftime("%b %d, %Y at %I:%M%P") %>
        </p>

        <p>
          <strong>Status:</strong>
          <%= @job.status %>
        </p>

        <p>
          <strong>Furnitures:</strong>
          <% @job.furnitures.each do |furn| %>
            <%= furn.category %>
          <% end %>
        </p>

        <% if @job.mover && @job.mover.id != session[:user_id] %>
          <p>
            <strong>Mover:</strong>
              <%= @job.mover.name %> <%= link_to "(profile)", user_path(@job.mover) %>
          </p>
        <% elsif @job.mover && @job.mover.id == session[:user_id] %>
        <p>
          <strong>Mover:</strong>
            You!
        </p>
        <% end %>

        <% if @job.poster.id != session[:user_id] %>
          <p>
            <strong>Poster:</strong>
              <%= @job.poster.name %> <%= link_to "(profile)", user_path(@job.poster) %>
          </p>
        <% elsif @job.poster.id == session[:user_id] %>
        <p>
          <strong>Poster:</strong>
            You!
        </p>
        <% end %>

        <% if @job.poster.id == session[:user_id] || (@job.mover && @job.mover.id == session[:user_id]) %>
          <p>
            <strong> Address:</strong>
              <%= @job.poster.address %>
          </p>
          <p>
            <strong> Phone Number:</strong>
              <%= @job.poster.phone_number %>
          </p>
          <p>
            <strong> Email:</strong>
              <%= @job.poster.email %>
          </p>
        <% end %>
      </div>
      <% if @job.status != "Pending" && (@job.mover.id == session[:user_id] || @job.poster.id == session[:user_id])%>
      <div class="col-xm-4">
        <iframe width="300" height="300" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/search?q=<%= @job.poster.address %>&key=AIzaSyAo2JzMkz3lUtKVH1nyMncrZnAcmHZDDis" allowfullscreen></iframe>
      </div>
      <% end %>
    </div>
    <div class="row">
      <% if @job.poster.id == session[:user_id] && @job.status != 'Completed' %>
        <%= button_to 'Edit', edit_job_path(@job), action: 'edit', method: :get, class: "btn btn-outline-secondary" %>
      <% end %>

      <% if @job.poster.id != session[:user_id] && @job.status == 'Pending' %>
        <%= button_to "Accept Job", accept_path(@job), action: 'accept', method: :patch, class: "btn btn-outline-secondary" %>
      <% end %>

      <% if (@job.poster_id == session[:user_id] || (@job.mover && @job.mover.id == session[:user_id])) && @job.status == 'Accepted' %>
        <%= button_to "Job Complete", complete_path(@job), action: 'complete', method: :patch, class: "btn btn-outline-secondary" %>
      <% end %>

      <% if (@job.poster.id == session[:user_id] || (@job.mover && @job.mover.id == session[:user_id])) && @job.status != "Canceled" && @job.status != "Archived" %>
        <%= button_to "Cancel Job", cancel_path(@job), action: 'cancel', method: :patch, class: "btn btn-outline-secondary" %>
      <% end %>

      <% if @job.poster.id == session[:user_id] && @job.status == "Canceled" %>
        <%= button_to "Job's Back On", uncancel_path(@job), action: 'uncancel', method: :patch, class: "btn btn-outline-secondary" %>
        <%= button_to "Delete Job", job_path, method: :delete, class: "btn btn-outline-secondary"%>
      <% end %>

      <% if (@job.poster.id == session[:user_id] || (@job.mover && @job.mover.id == session[:user_id])) && @job.status == "Completed" %>
        <%= button_to "Archive", archive_path(@job), action: 'archived', method: :patch, class: "btn btn-outline-secondary" %>
      <% end %>
    </div>
</div>

<br>

<div class="job-card">
  <% if @job.status == "Completed" %>
    <h3>Reviews</h3>

    <div>
      <% @job.reviews.each do |review| %>
        <p>
        <% review.rating.times do %>
          <%= "⭐" %>
        <% end %><br>
        <%= review.content %>
        -- <%= link_to review.user.username, review.user %></p><br>
      <% end %>
    </div>
  <% end %>

  <% if (session[:user_id] == @job.poster_id || session[:user_id] == @job.mover_id) && @job.status == "Completed" %>
    <%= form_for @job.reviews.build do |f| %>
      <%= f.hidden_field :job_id, :value => @job.id %>
      <%= f.hidden_field :user_id, :value => session[:user_id] %>
      <%= f.label "Write a Review" %>
      <%= f.text_area :content%><br>
      <%= f.label :rating %>
      <%= f.radio_button :rating, 1 %>
      <%= f.radio_button :rating, 2 %>
      <%= f.radio_button :rating, 3 %>
      <%= f.radio_button :rating, 4 %>
      <%= f.radio_button :rating, 5 %><br><br>
      <%= f.submit %>
    <% end %>
  <% end %>
</div>